name: listaa
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  animated_text_kit: ^4.2.3
  bottom_picker: ^3.2.1
  calendar_date_picker2: ^2.0.1
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^19.3.0
  flutter_native_splash: ^2.4.6
  flutter_popup: ^3.3.9
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  flutter_timezone: ^4.1.1
  get: ^4.7.2
  google_mlkit_barcode_scanning: ^0.14.1
  group_button: ^5.3.4
  image_picker: ^1.1.2
  intl: ^0.20.2
  mobile_scanner: ^7.0.1
  overflow_text_animated: ^0.0.6
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  qr_flutter: ^4.1.0
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  timezone: ^0.10.1
  url_launcher: ^6.3.2
  workmanager: ^0.8.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/templates/
    - assets/svgs/icons/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app_icon.png
  branding: null
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
